### ISSUE TITLE
I am not seeing the image upload section

### ISSUE THREAD

**Issue by asifrafeeq** [aliabdulaziz/laravel-extended-user#1]
Hi, 

This is one of the nicest plugins which I have ever used, just I am facing a small issue, when I go to profile, I am unable to upload my image as I am not seeing the image upload input.
plz guide me...
thanks a lot in advance  
![snap07](https://user-images.githubusercontent.com/2939341/108476076-6a1e1180-72b3-11eb-8c5f-710cea6a6ad8.PNG)

**Comment by aliabdulaziz** [comment]
This is a very old project which I unfortunately have no time to maintain but feel free to send PRs and I will merge them
